version: '3.8'

services:
  seo-tool:
    build: .
    ports:
      - "9001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - seo-network

networks:
  seo-network:
    driver: bridge
