services:
  seo-tool:
    image: axxmet/ahmets-special-seo-tool:latest
    container_name: ahmets-seo-tool-production
    restart: unless-stopped
    ports:
      - "1389:80"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Istanbul
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=10m
      - /var/run:noexec,nosuid,size=10m
      - /tmp:noexec,nosuid,size=10m

networks:
  default:
    name: seo-tool-network
